# Docker Compose override file for frontend migration
# Use with: docker compose -f docker-compose.yml -f docker-compose.migration.yml up

services:
  # Override backend CORS to support both frontends
  backend:
    environment:
      - BACKEND_CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://frontend:3000,http://frontend-simple

  # Add labels for easy identification
  frontend:
    labels:
      - "migration.type=react"
      - "migration.status=current"
      - "migration.port=3000"

  frontend-simple:
    labels:
      - "migration.type=vanilla"
      - "migration.status=testing"
      - "migration.port=3001"

  # Optional: Add a simple nginx proxy for A/B testing
  migration-proxy:
    image: nginx:alpine
    container_name: image2model-migration-proxy
    ports:
      - "8080:80"  # Testing proxy on port 8080
    volumes:
      - ./docker/nginx/migration-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - frontend-simple
    networks:
      - image2model-network
    profiles:
      - migration  # Only start with --profile migration