# Removed deprecated version field - Docker Compose v2+ ignores this

services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    container_name: image2model-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image2model
    # Port removed for security - access via Docker network only
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - image2model-network

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: image2model-redis
    # Port removed for security - access via Docker network only
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - image2model-network

  # FastAPI backend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: production
    container_name: image2model-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/image2model
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - BACKEND_CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      # API keys should be set in .env file:
      # - FAL_API_KEY=${FAL_API_KEY}
      # - API_KEY=${API_KEY}
      # - ADMIN_API_KEY=${ADMIN_API_KEY}
    env_file:
      - .env
    volumes:
      - ./backend:/app:delegated
      - backend_uploads:/app/uploads
      - backend_results:/app/results
      - backend_models:/app/models
      - /app/__pycache__
      - /app/.pytest_cache
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - image2model-network
    restart: unless-stopped

  # Celery worker for background tasks
  worker:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: production
    container_name: image2model-worker
    # Disable health check - not applicable for Celery workers
    healthcheck:
      test: ["CMD", "true"]
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/image2model
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      # API keys should be set in .env file
    env_file:
      - .env
    volumes:
      - ./backend:/app:delegated
      - backend_uploads:/app/uploads
      - backend_results:/app/results
      - backend_models:/app/models
      - /app/__pycache__
      - /app/.pytest_cache
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=4 -Q default,batch_processing,model_generation,maintenance,priority --max-tasks-per-child=50
    networks:
      - image2model-network
    restart: unless-stopped

  # Additional Celery worker dedicated to model generation
  worker-model:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: production
    container_name: image2model-worker-model
    # Disable health check - not applicable for Celery workers
    healthcheck:
      test: ["CMD", "true"]
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/image2model
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      # API keys should be set in .env file
    env_file:
      - .env
    volumes:
      - ./backend:/app:delegated
      - backend_uploads:/app/uploads
      - backend_results:/app/results
      - backend_models:/app/models
      - /app/__pycache__
      - /app/.pytest_cache
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=3 -Q model_generation --max-tasks-per-child=20 -n worker-model@%h
    networks:
      - image2model-network
    restart: unless-stopped

  # Celery monitoring (optional)
  flower:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: production
    container_name: image2model-flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./backend:/app:delegated
    depends_on:
      - redis
      - worker
    command: celery -A app.core.celery_app flower --port=5555
    networks:
      - image2model-network
    restart: unless-stopped

  # Frontend (Svelte)
  frontend:
    build:
      context: ./frontend-svelte
      dockerfile: Dockerfile
    container_name: image2model-frontend
    ports:
      - "3000:3000"  # Svelte frontend port
    environment:
      - NODE_ENV=production
      - ORIGIN=http://localhost:3000
      - API_KEY=${API_KEY}
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - image2model-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  image2model-network:
    driver: bridge
    name: image2model-network

volumes:
  postgres_data:
    name: image2model-postgres-data
  redis_data:
    name: image2model-redis-data
  backend_uploads:
    name: image2model-backend-uploads
  backend_results:
    name: image2model-backend-results
  backend_models:
    name: image2model-backend-models
